
<?php   $categoryIcon = $post->getCategoryIcon(); ?>

<aside class="post post-caption-wrapper">
    <div class="post-caption">
        <div class="<?php echo $categoryIcon->color; ?> circle category-icon">
            <i class="fa <?php echo $categoryIcon->class; ?>"></i>
        </div>
        <div class="more bottom">
            Read more articles from 
            <a href="https://www.google.com/#q=site:blog.teachboost.com+<?php echo str_replace( " ", "+", $category->name ); ?>"><?php echo $category->name; ?></a>.
        </div>
        <div class="subscribe clear">
            <strong>Like this post?</strong>
            <br />
            Get updates by email!<br />
            <a href="javascript:;" 
               class="gray button subscribe-button" 
               id="subscribe-button">Subscribe to LaunchPad</a>
            <form action="http://teachboost.us4.list-manage.com/subscribe/post?u=bb91eae94006986230e4e46f0&amp;id=016c3a4dba" 
                  method="post" 
                  id="mc-embedded-subscribe-form" 
                  name="mc-embedded-subscribe-form" 
                  class="validate" 
                  style="display:none; margin-bottom:25px;" novalidate>
                <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email address" style="margin: 10px 0 5px; width: 175px;" required>
                <!-- real people should not fill this in and expect good things
                     do not remove this or risk form bot signups -->
                <div style="position: absolute; left: -5000px;">
                    <input type="text" name="b_bb91eae94006986230e4e46f0_016c3a4dba" value="">
                </div>
                <div class="clear">
                    <input type="submit" value="Subscribe!" name="subscribe" id="mc-embedded-subscribe" class="blue button fontsize-15" />
                </div>
            </form>
        </div>
        <div class="share addthis_toolbox addthis_default_style">
            <a class="addthis_button_preferred_1"></a>
            <a class="addthis_button_preferred_2"></a>
            <a class="addthis_button_preferred_3"></a>
            <a class="addthis_button_preferred_4"></a>
            <a class="addthis_button_compact"></a>
            <a class="addthis_counter addthis_bubble_style"></a>
        </div>
        <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-535a73cb4ec3e51a"></script>
    </div>
</aside>
