<?php   $categoryIcon = $post->getCategoryIcon(); ?>

<aside class="post post-caption-wrapper">
    <div class="post-caption">
        <div class="<?php echo $categoryIcon->color; ?> circle category-icon">
            <i class="fa <?php echo $categoryIcon->class; ?>"></i>
        </div>
<?php   if ( $category ): ?>
        <div class="more bottom">
            Read more articles from
            <a href="https://www.google.com/#q=site:blog.teachboost.com+<?php echo str_replace( " ", "+", $category->name ); ?>"><?php echo $category->name; ?></a>.
        </div>
<?php   endif; ?>

<?php   if ( is_object( $posts ) && count( $posts ) > 1 ): ?>

        <h3 class="centered-text padding-top-10">Recent Posts</h3>
        <ul class="article-list">

<?php       foreach ( $posts as $post ): ?>
<?php           if ( str_eq( $post->status, "published" ) ): ?>

            <li class="article <?php echo $post->getCategoryIcon()->color; ?>">
                <a href="<?php echo $post->getPath(); ?>">
                    <?php echo $post->title; ?>
                </a>
            </li>

<?php           endif; ?>
<?php       endforeach; ?>

        </ul>
<?php   endif; ?>

        <h3 class="centered-text padding-top-20">Blog Search</h3>
        <p class="centered-text line-height-1-4">Enter a tag, author, or topic here to search:</p>
        <input type="text" class="search" id="search-query" />
        <a class="blue button" href="javascript:;" id="search-submit">Search</a>

        <small class="blocked centered-text padding-top-20">
            <a href="https://teachboost.com">Back to TeachBoost</a>
        </small>
    </div>
</aside>
