<footer class="site-footer">
    <div class="inner column">
        <div class="logo">
            <a class="blog-logo" href="<?php echo $this->url->get( '' ); ?>">
                <span class="logotext">TeachBoost</span>
            </a>
        </div>
        <div class="learnmore">
            <h4>Learn More</h4>
            <a href="https://teachboost.com/company/about" class="item">What is TeachBoost?</a>
            <a href="https://teachboost.com/company/team" class="item">Our Team</a>
            <a href="https://teachboost.com/contact" class="item">Contact Information</a>
            <a href="https://teachboost.com/terms/privacy" class="item">Privacy Policy</a>
            <a href="https://teachboost.com/terms/service" class="item">Terms &amp; Conditions</a>
            <a href="https://teachboost.com/terms/brand" class="item">Brand Usage Guidelines</a>
            <a href="http://blog.teachboost.com" class="item">Blog</a>
        </div>
        <div class="solutions">
            <h4><a href="https://teachboost.com/products">Products</a></h4>
            <a href="https://teachboost.com/products/observations" class="item">Observations &amp; Evaluations</a>
            <a href="https://teachboost.com/products/coaching" class="item">Coaching &amp; Mentorship</a>
            <a href="https://teachboost.com/products/pd" class="item">Professional Development</a>
        </div>
        <div class="copyright">
            <h4>Copyright Information</h4>
            <p class="top-margin-5 no-bottom-margin">
                &copy; 2007-14 Schoolbinder, Inc.
            </p>
            <p>
                All school content and data property of and copyright its respective users.
                Please see our terms for all policies in intellectual property. Application
                icons provided by <a href="http://fontawesome.io" class="white-text underline">Font Awesome</a>.
            </p>
        </div>
        <div class="clear"></div>
    </div>
</footer>
