<footer class="site-footer">
    <div class="inner column">
        <div class="logo">
            <a class="blog-logo" href="<?php echo $this->url->get( '' ); ?>">
                <span class="logotext">TeachBoost</span>
            </a>
        </div>
        <div class="learnmore">
            <h4>Learn More</h4>
            <a href="https://teachboost.com/company/about" class="item">What is TeachBoost?</a>
            <a href="https://teachboost.com/company/team" class="item">Our Team</a>
            <a href="https://teachboost.com/contact" class="item">Contact Information</a>
            <a href="https://teachboost.com/terms/privacy" class="item">Privacy Policy</a>
            <a href="https://teachboost.com/terms/service" class="item">Terms &amp; Conditions</a>
            <a href="https://teachboost.com/terms/brand" class="item">Brand Usage Guidelines</a>
            <a href="http://blog.teachboost.com" class="item">Blog</a>
        </div>
        <div class="solutions">
            <h4><a href="https://teachboost.com/products">Products</a></h4>
            <a href="https://teachboost.com/products/observations" class="item">Observations &amp; Evaluations</a>
            <a href="https://teachboost.com/products/coaching" class="item">Coaching &amp; Mentorship</a>
            <a href="https://teachboost.com/products/pd" class="item">Professional Development</a>
        </div>
        <div class="copyright">
            <h4>Copyright Information</h4>
            <p class="top-margin-5 no-bottom-margin">
                &copy; 2007-15 Schoolbinder, Inc.
            </p>
            <p style="margin: 7px 0;">
                All school content and data property of and copyright its respective users.
            </p>
            <p>
                Please see our terms for all policies in intellectual property.
            </p>
        </div>
        <div class="clear"></div>
    </div>
</footer>

<section id="flip">
    <a class="close" href="javascript:;"><i class="fa fa-times"></i></a>
    <h2>Get weekly articles on instructional leadership!</h2>

    <form accept-charset="UTF-8"
          enctype="multipart/form-data"
          id="hsForm_61e4bba3-1b70-4bc7-bf8f-6c2881fd2232"
          class="hs-form stacked"
          action="https://forms.hubspot.com/uploads/form/v2/436965/61e4bba3-1b70-4bc7-bf8f-6c2881fd2232"
          method="POST"
          novalidate="novalidate">
        <input class="hs-input input-half"
               type="text"
               id="firstname-61e4bba3-1b70-4bc7-bf8f-6c2881fd2232"
               name="firstname"
               value=""
               placeholder="First name"
               style="margin-right: 13px;" />
        <input class="hs-input input-half"
               type="text"
               id="lastname-61e4bba3-1b70-4bc7-bf8f-6c2881fd2232"
               name="lastname"
               value=""
               placeholder="Last name" />
        <input class="hs-input input"
               type="email"
               required="required"
               id="email-61e4bba3-1b70-4bc7-bf8f-6c2881fd2232"
               name="email"
               value=""
               placeholder="Email address" />
        <input class="hs-input input"
               type="text"
               id="company-61e4bba3-1b70-4bc7-bf8f-6c2881fd2232"
               name="company"
               value=""
               placeholder="Organization" />

        <input type="submit" class="big blue button" value="Subscribe to Updates" />
    </form>
    <small class="message">We won't spam you ever. Unsubscribe anytime.</small>
</section>

<section id="subMessage">
    <h3>Thank you for subscribing!</h3>
    <p>You'll start receving updates for future blog posts and you can always unsubscribe at any time.</p>
</section>
