<section class="post-header-wrapper">

    <!-- Sales Banner -->
    <section class="top-banner centered-text" id="salesBanner">
        <div class="wrapper">
            Have questions<span class="hide-568"> about TeachBoost</span>?
            <strong><span class="hide-568">Give us a call at </span>(844) 542-6678</strong>
            or
            <a href="http://connect.teachboost.com/info"
               title="Get in touch with us"
               class="small green button left-margin-5"
               target="blank"
               style="margin: -2px 0 0 5px;">Get in Touch!</a>
        </div>
    </section>

    <header class="column post-header clearfix">
        <a class="mobile-burger post" id="mobile-burger" href="javascript:;" data-state="off">
            <i class="fa fa-bars"></i>
        </a>
        <a class="blog-logo float-left" href="https://teachboost.com">
            <img src="<?php echo $this->url->get( 'img/mark.png' ); ?>" class="logomark" alt="TeachBoost" />
            <span class="logotext">TeachBoost</span>
        </a>
        <nav class="header-nav">
            <ul class="clearfix">
                <li class="btn node">
                    <a href="https://connect.teachboost.com/info" title="Get in touch with us" class="gray button">Get in Touch!</a>
                </li>
                <li class="btn node">
                    <a href="https://teachboost.com/login" title="Sign in to TeachBoost" class="blue button">Sign In</a>
                </li>
                <li class="link node active">
                    <a href="http://blog.teachboost.com" title="The TeachBoost Blog" class="">Blog</a>
                </li>
                <li class="link node">
                    <a href="https://teachboost.com/contact" title="Contact us">Contact</a>
                </li>
                <li class="link node">
                    <a href="https://teachboost.com/company/about" title="About TeachBoost">About</a>
                    <ul class="menu about">
                        <li class="item span-link">
                            <a href="https://teachboost.com/company/about">What is TeachBoost?</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/contact">Contact Info</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/company/team">The Team</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/company/events">News &amp; Events</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/terms/privacy">Privacy Policy</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/terms">Terms &amp; Conditions</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/terms/brand">Brand Use Guidelines</a>
                        </li>
                    </ul>
                </li>
                <li class="link node">
                    <a href="https://teachboost.com/products" title="Instructional Leadership Platform">Products</a>
                    <ul class="menu solutions">
                        <li class="item span-text">
                            <a href="https://teachboost.com/products">Instructional Leadership Platform</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/products/observations">
                                Observations &amp; Evaluations
                            </a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/products/coaching">
                                Coaching &amp; Mentorship
                            </a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/products/pd">
                                Professional Development
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
</section>
