<section class="post-header-wrapper">
    <header class="column post-header">
        <a class="blog-logo" href="<?php echo $this->url->get( '' ); ?>">
            <img src="<?php echo $this->url->get( 'img/mark.png' ); ?>" class="logomark" alt="TeachBoost" />
            <span class="logotext">TeachBoost</span>
        </a>
        <nav class="header-nav">
            <ul class="clearfix">
                <li class="btn node">
                    <a href="https://teachboost.com/contact/form#auto=1" title="Get in touch with us" class="gray button">Get in Touch!</a>
                </li>
                <li class="btn node">
                    <a href="https://teachboost.com/login" title="Sign in to TeachBoost" class="blue button">Sign In</a>
                </li>
                <li class="link node active">
                    <a href="http://blog.teachboost.com" title="The TeachBoost Blog" class="">Blog</a>
                </li>
                <li class="link node">
                    <a href="https://teachboost.com/contact" title="Contact us">Contact</a>
                </li>
                <li class="link node">
                    <a href="https://teachboost.com/company/about" title="About TeachBoost">About</a>
                    <ul class="menu about">
                        <li class="item span-link">
                            <a href="https://teachboost.com/company/about">What is TeachBoost?</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/contact">Contact Info</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/company/team">The Team</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/company/events">News &amp; Events</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/terms/privacy">Privacy Policy</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/terms">Terms &amp; Conditions</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/terms/brand">Brand Use Guidelines</a>
                        </li>
                    </ul>
                </li>
                <li class="link node">
                    <a href="https://teachboost.com/solutions" title="TeachBoost's Solutions">Solutions</a>
                    <ul class="menu solutions">
                        <li class="item span-link">
                            <a href="https://teachboost.com/solutions/teachers">Teachers</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/solutions/schools">School Leaders</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/solutions/districts">District Leaders</a>
                        </li>
                        <li class="item span-link">
                            <a href="https://teachboost.com/solutions/organizations">Organizations</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
</section>
