<section class="mobile-menu<?php echo (isset($post)) ? ' post' : ''; ?>" id="mobile-menu">
    <ul>
        <li><a href="http://blog.teachboost.com/">TeachBoost LaunchPad</a></li>
        <li><a href="http://teachboost.com/dashboard">Go to Your Dashboard</a></li>
        <li><a href="https://www.google.com/#q=site:blog.teachboost.com">Search Blog Posts</a></li>
        <li><a href="http://teachboost.us4.list-manage.com/subscribe?u=bb91eae94006986230e4e46f0&amp;id=016c3a4dba">Subscribe by Email to New Posts</a></li>
    </ul>
</section>