<?php   $cat_icon = category_icon( $category->slug ); ?>

<aside class="post-caption-wrapper">
    <div class="post-caption">
        <div class="<?php echo $cat_icon[1]; ?> circle category-icon">
            <i class="fa <?php echo $cat_icon[0]; ?>"></i>
        </div>
        <div class="more bottom">
            Read more articles from 
            <a href="#"><?php echo $category->name; ?></a>.
        </div>
        <div class="subscribe clear">
            <strong>Like this post?</strong><br />
            Get updates by email!<br />
            <a href="#" class="gray button subscribe-button">Subscribe to LaunchPad</a>
        </div>
        <div class="share addthis_toolbox addthis_default_style">
            <a class="addthis_button_preferred_1"></a>
            <a class="addthis_button_preferred_2"></a>
            <a class="addthis_button_preferred_3"></a>
            <a class="addthis_button_preferred_4"></a>
            <a class="addthis_button_compact"></a>
            <a class="addthis_counter addthis_bubble_style"></a>
        </div>
        <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-535a73cb4ec3e51a"></script>
    </div>
</aside>
