<aside class="post-caption-wrapper home">
    <div class="post-caption">

<?php /*
            <div class="categories home-slice">
                <h3>Posts by Category</h3>

<?php   if ( count( $categories ) > 0 ): ?>
<?php       $total = count( $categories ); ?>
<?php       $i = 1; ?>
<?php       foreach ( $categories as $category ): ?>

                <a href="<?php echo $category->slug; ?>" class="category-link">
                    <?php echo $category->name; ?>
                </a> <?php echo ( $i < $total ) ? '&middot;' : ''; ?>
<?php           $i++; ?>
<?php       endforeach; ?>
<?php   endif; ?>

<?php */ ?>

        <div class="categories home-slice">
            <h3>Blog Search</h3>
            <span>Enter a tag, author, or topic here to search:</span>
            <input type="text" class="search" id="search-query" />
            <a class="blue button" href="javascript:;" id="search-submit">Search</a>
        </div>

        <div class="subscribe">
            <h3>Subscribe to Updates</h3>
            <span>We'll email you when there are new posts here:</span>
            <noscript>
                <form action="http://teachboost.us4.list-manage.com/subscribe/post?u=bb91eae94006986230e4e46f0&amp;id=016c3a4dba"
                      method="post"
                      id="mc-embedded-subscribe-form"
                      name="mc-embedded-subscribe-form"
                      class="validate" novalidate>
                    <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL"
                        placeholder="Email address" style="margin: 10px 0 5px; width: 175px;" required>
                    <!-- real people should not fill this in and expect good things
                         do not remove this or risk form bot signups -->
                    <div style="position: absolute; left: -5000px;">
                        <input type="text" name="b_bb91eae94006986230e4e46f0_016c3a4dba" value="">
                    </div>
                    <div class="clear">
                        <input type="submit" value="Subscribe!" name="subscribe" id="mc-embedded-subscribe" class="blue button fontsize-15" />
                    </div>
                </form>
            </noscript>
            <a href="javascript:;"
               class="gray button subscribe-button home"
               id="subscribe-button"
               style="display:none;">
                <i class="fa fa-envelope-o"></i>&nbsp;
                Subscribe by Email
            </a>
            <form action="http://teachboost.us4.list-manage.com/subscribe/post?u=bb91eae94006986230e4e46f0&amp;id=016c3a4dba"
                  method="post"
                  id="mc-embedded-subscribe-form"
                  name="mc-embedded-subscribe-form"
                  class="validate"
                  style="display:none;" novalidate>
                <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL"
                    placeholder="Email address" style="margin: 10px 0 5px; width: 175px;" required>
                <!-- real people should not fill this in and expect good things
                     do not remove this or risk form bot signups -->
                <div style="position: absolute; left: -5000px;">
                    <input type="text" name="b_bb91eae94006986230e4e46f0_016c3a4dba" value="">
                </div>
                <div class="clear">
                    <input type="submit" value="Subscribe!" name="subscribe" id="mc-embedded-subscribe" class="blue button fontsize-15" />
                </div>
            </form>
            <p>Or get updates via RSS:</p>
            <a class="orange button" href="posts/rss">
              <i class="fa fa-rss-square"></i>&nbsp;
              Subscribe to RSS
            </a>
        </div>

        <!--<div class="testimonial clear">
            <strong>Hear what our <br />customers are saying!</strong>
            <a href="http://blog.teachboost.com/2014/06/introducing-the-teachboost-customer-spotlight-video">
                <i class="fa fa-play-circle"></i>
            </a>
        </div>-->
    </div>
</aside>
