
<header class="site-head">
    <div class="vertical">
        <div class="site-head-content inner">
            <a class="blog-logo" href="<?php echo $this->url->get( '' ); ?>">
                <img src="<?php echo $this->url->get( 'img/mark.png' ); ?>" alt="Blog Logo" />
            </a>
            <h1 class="blog-title">Blog Title</h1>
            <h2 class="blog-description">Blog Description</h2>
        </div>
    </div>
</header>

<main class="content" role="main">

<?php   foreach ( $posts as $post ): ?>

    <article class="">
        <header class="post-header">
            <span class="post-meta">
                <?php echo date( DATE_DAY_NAME_YEAR, strtotime( $post->post_date ) ); ?>
            </span>
            <h2 class="post-title">
                <a href="<?php echo $post->getPath(); ?>">
                    <?php echo $post->title; ?>
                </a>
            </h2>
        </header>
        <section class="post-excerpt">
            <p>
                <?php echo $post->excerpt; ?>&hellip;
                <a class="read-more" href="<?php echo $post->getPath(); ?>">&raquo;</a>
            </p>
        </section>
    </article>

<?php   endforeach; ?>

</main>