
<main class="content" role="main">

<?php   $this->partial( 'partials/header' ); ?>
<?php   $this->partial( 'partials/caption' ); ?>

    <article>

<?php   $this->partial( 'partials/sideboard' ); ?>

        <h1 class="post-title">
            <?php echo $post->title; ?>
        </h1>

        <time class="post-date">
            Posted on <?php echo date( "M d, Y", strtotime( $post->post_date ) ); ?>.
        </time>

        <section class="post-content">
            <?php echo $post->getHtmlBody(); ?>
        </section>

        <section class="byline">
            <strong><?php echo $post->getAuthor()->name; ?></strong><br />
            <span class="title"><?php echo $post->getAuthor()->bio; ?></span>
        </section>

        <footer class="post-footer">

<?php   /*
            <section class="share">
                <h4>Share this post</h4>
                <a class="icon-twitter" href="https://twitter.com/share?text={{encode title}}&amp;url={{url absolute="true"}}"
                    onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
                    <span class="hidden">Twitter</span>
                </a>
                <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u={{url absolute="true"}}"
                    onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
                    <span class="hidden">Facebook</span>
                </a>
                <a class="icon-google-plus" href="https://plus.google.com/share?url={{url absolute="true"}}"
                   onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
                    <span class="hidden">Google+</span>
                </a>
            </section>
        */ ?>
        </footer>
    </article>

</main>
