<?php   $this->partial( 'partials/menu', array( 'post' => TRUE ) ); ?>

<main class="content" role="main">

<?php   $this->partial( 'partials/header' ); ?>
<?php   $this->partial( 'partials/caption' ); ?>

    <article class="post">

        <h1 class="post-title">
            <?php echo $post->title; ?>
        </h1>

        <time class="post-date">
            Posted on <?php echo date( "M d, Y", strtotime( $post->post_date ) ); ?>
        </time>

        <section class="post-content">
            <?php echo $post->getHtmlBody(); ?>
        </section>

        <section class="byline">
            <strong><?php echo $post->getAuthor()->name; ?></strong><br />
            <span class="title"><?php echo $post->getAuthor()->bio; ?></span>
        </section>

<?php   $this->partial( 'partials/sideboard' ); ?>

        <section class="comments">
            <div id="disqus_thread"></div>
            <script type="text/javascript">
                /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                var disqus_shortname = 'teachboost'; // required: replace example with your forum shortname

                /* * * DON'T EDIT BELOW THIS LINE * * */
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
        </section>
        
    </article>

</main>
