<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <title>TeachBoost LaunchPad</title>
    <meta name="description" content="" />

    <meta name="HandheldFriendly" content="True" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

<?php   if ( $this->config->app->environment == 'production' ): ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->url->get( 'css/build.css' ); ?>">
<?php   else: ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->url->get( 'css/app.css' ); ?>">
<?php   endif; ?>
    <link href='http://fonts.googleapis.com/css?family=Signika:400,700' 
        rel='stylesheet' type='text/css'>
</head>
<body class="home">

    <?php echo $this->getContent() ?>

<?php   if ( $this->dispatcher->getControllerName() != 'login' ): 
            $this->partial( 'partials/footer' ); 
        endif; ?>

<?php   if ( $this->config->app->environment == 'production' ): ?>
    <script src="<?php echo $this->url->get( 'js/dist/build.js' ); ?>"></script>
<?php   else: ?>
    <script src="<?php echo $this->url->get( 'js/vendor/jquery.js' ); ?>"></script>
<?php   endif; ?>
    <script type="text/javascript" src="<?php echo $this->url->get( 'js/main.js' ); ?>"></script>

</body>
</html>