<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <title>TeachBoost LaunchPad</title>
    <meta name="description" content="" />

    <meta name="HandheldFriendly" content="True" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

<?php   if ( $this->config->app->environment == 'production' ): ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->url->get( 'css/build.css' ); ?>">
<?php   else: ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->url->get( 'css/app.css' ); ?>">
<?php   endif; ?>
    <link href='http://fonts.googleapis.com/css?family=Signika:400,700' 
        rel='stylesheet' type='text/css'>
</head>
<body class="">

    <?php echo $this->getContent() ?>

    <footer class="site-footer">
        <div class="inner column">
            <div class="logo">
                <a class="blog-logo" href="<?php echo $this->url->get( '' ); ?>">
                    <span class="logotext">TeachBoost</span>
                </a>
            </div>
            <div class="learnmore">
                <h4>Learn More</h4>
                <a href="https://teachboost.com/company/about" class="item">What is TeachBoost?</a>
                <a href="https://teachboost.com/company/team" class="item">Our Team</a>
                <a href="https://teachboost.com/contact" class="item">Contact Information</a>
                <a href="https://teachboost.com/terms/privacy" class="item">Privacy Policy</a>
                <a href="https://teachboost.com/terms/service" class="item">Terms &amp; Conditions</a>
                <a href="https://teachboost.com/terms/brand" class="item">Brand Usage Guidelines</a>
                <a href="http://blog.teachboost.com" class="item">Blog</a>
            </div>
            <div class="solutions">
                <h4>Solutions</h4>
                <a href="https://teachboost.com/solutions/teachers" class="item">Teachers</a>
                <a href="https://teachboost.com/solutions/schools" class="item">School Leaders</a>
                <a href="https://teachboost.com/solutions/districts" class="item">District Leaders</a>
                <a href="https://teachboost.com/solutions/organizations" class="item">Organizations</a>
            </div>
            <div class="copyright">
                <h4>Copyright Information</h4>
                <p class="top-margin-5 no-bottom-margin">
                    &copy; 2007-14 Schoolbinder, Inc.
                </p>
                <p>
                    All school content and data property of and copyright its respective users.
                    Please see our terms for all policies in intellectual property. Application
                    icons provided by <a href="http://fontawesome.io" class="white-text underline">Font Awesome</a>.
                </p>
            </div>
            <div class="clear"></div>
        </div>
    </footer>

<?php   if ( $this->config->app->environment == 'production' ): ?>
    <script src="<?php echo $this->url->get( 'js/dist/build.js' ); ?>"></script>
<?php   else: ?>
    <script src="<?php echo $this->url->get( 'js/vendor/jquery.js' ); ?>"></script>
<?php   endif; ?>
    <script type="text/javascript" src="<?php echo $this->url->get( 'js/main.js' ); ?>"></script>

</body>
</html>